name: my_workflow
on:
  push:
    branches:
      - 'v[0-9].[0-9]'
jobs:
    workflow:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: scan
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            format: 'table'
            output: 'trivy-results.txt'
            severity: 'CRITICAL'

        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_MESSAGE: 'Post Content :jerry'
            SLACK_TITLE: CICD

        