name: my_workflow
on:
    push:
        branches:
            - 'v[0-9].[0-9].*'

jobs:
    workflow:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        