name: my_workflow
on:
  push:
    branches:
      - 'v[0-9].[0-9]'
jobs:
    workflow:
        runs-on: ubuntu-latest

        steps:
        - name: Check Commit Message
          run: |
            if [[ $(git log --format=%B -n 1 ${{ github.sha }}) == '#NORUN'* ]]; then
              echo "Commit message starts with #NORUN. Skipping the pipeline."
              exit 0  # Exit with success to skip the rest of the steps
            fi

        - name: Checkout code
          uses: actions/checkout@v4
          
        - name: scan
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            format: 'table'
            output: 'trivy-results.txt'
            severity: 'CRITICAL, HIGH'      
              
        - name: Slack Notification
          if: failure()
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_MESSAGE: 'fail trivy scan, see uploaded report'
            SLACK_TITLE: Scan failed-jerry

        - uses: MeilCli/slack-upload-file@v3
          if: failure()
          with:
            slack_token: ${{ secrets.SLACK_TOKEN }}
            channel_id: ${{ secrets.CHANNEL_ID }}
            initial_comment: 'scan report by jerry'
            file_path: 'trivy-results.txt'

        - name: Install Cosign
          uses: sigstore/cosign-installer@v3.1.1
          with: 
            cosign-release: 'v2.2.0'

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
          
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: fortunes
            push: true
            tags: jerry975/go-fortune:abcd1234
            #file: fortunes/

        - name: Sign image with a key
          run: |
            cosign sign --yes --key env://COSIGN_PRIVATE_KEY jerry975/go-fortune@sha256:b71d5fbc694661e73680d0036d8be87a0d84ca42497cebb3065fa1de91bca9cf
          env:
            TAGS: jerry975/go-fortune:abcd1234
            COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
            COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
            DIGEST: ${{ steps.build-and-push.outputs.digest }}

        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            
            SLACK_TITLE: Image build and signed
            SLACK_MESSAGE: |
              'Name: Liu Jiarui
              Metriculation: A0285883J
              Email: e1221695@u.nus.edu
              Git: https://github.com/jerry975/fortunes.git
              Image: https://hub.docker.com/repository/docker/jerry975/go-fortune/general'